name: Auto-Approve Dependabot PRs
on:
  pull_request:
    branches: [ master ]

# Runs a job to auto-approve PRs made by dependabot so
# they can be auto-merged by dependabot
jobs:
  dependabot-auto-approve:
    runs-on: ubuntu-latest

    # Run the auto-approve script twice (needs 2 reviewers)
    steps:
    - uses: hmarr/auto-approve-action@v2.1.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: hmarr/auto-approve-action@v2.1.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
